name: gr26_tcm

services:
  db:
    image: postgres:17-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mapache
      POSTGRES_USER: gr26
      POSTGRES_PASSWORD: gr26

volumes:
  pgdata:
