FROM python:3.12-slim-bookworm

RUN pip install --no-cache-dir uv

WORKDIR /app
COPY pyproject.toml ./
RUN uv pip install --system . watchdog

CMD ["watchmedo", "auto-restart", \
     "--directory=/app", \
     "--pattern=*.py", \
     "--recursive", \
     "--", \
     "python", "main.py"]
